package bridge

import (
	"encoding/hex"
	"testing"
)

// All vectors generated by driving the Python helpers in trace_simulator.py.

type varintVec struct {
	n int
	x string
}

var varintVecs = []varintVec{
	{0, "00"},
	{1, "01"},
	{127, "7f"},
	{128, "8001"},
	{256, "8002"},
	{16383, "ff7f"},
	{16384, "808001"},
	{1 << 32, "8080808010"},
}

func TestVarintEncode(t *testing.T) {
	for _, v := range varintVecs {
		got := hex.EncodeToString(VarintEncode(v.n))
		if got != v.x {
			t.Errorf("VarintEncode(%d) = %s, want %s", v.n, got, v.x)
		}
		if want := len(v.x) / 2; VarintLen(v.n) != want {
			t.Errorf("VarintLen(%d) = %d, want %d", v.n, VarintLen(v.n), want)
		}
	}
}

func TestPackBR(t *testing.T) {
	cases := []struct {
		depth int
		bloom string
		want  string
	}{
		{0, "", "00"},
		{0, "ff01", "00ff01"},
		{1, "61616262", "0161616262"},
		{127, "00000000", "7f00000000"},
		{128, "ffffff", "8001ffffff"},
	}
	for _, c := range cases {
		bloom, _ := hex.DecodeString(c.bloom)
		got := hex.EncodeToString(PackBR(c.depth, bloom))
		if got != c.want {
			t.Errorf("PackBR(%d, %s) = %s, want %s", c.depth, c.bloom, got, c.want)
		}
	}
}

func TestHAAppendEntry(t *testing.T) {
	type step struct {
		sid     string
		depth   int
		want    string // empty want means HAAppendEntry should be a no-op (Python returned None)
		isNone  bool
	}
	steps := []step{
		{"8ee27a115b6fa625", 0, "8ee27a115b6fa62500", false},
		{"98655be61af2ecc4", 5, "8ee27a115b6fa6250098655be61af2ecc405", false},
		{"0", 7, "8ee27a115b6fa6250098655be61af2ecc405", true},  // Python returns None; ha unchanged
		{"zz", 9, "8ee27a115b6fa6250098655be61af2ecc405", true}, // ditto
	}
	ha := []byte{}
	for _, s := range steps {
		got := HAAppendEntry(ha, s.sid, s.depth)
		gotHex := hex.EncodeToString(got)
		if gotHex != s.want {
			t.Errorf("HAAppendEntry sid=%q depth=%d -> %s, want %s", s.sid, s.depth, gotHex, s.want)
		}
		ha = got
	}
}

func TestPackCGPBBR(t *testing.T) {
	cases := []struct {
		depth         int
		bloom, ha, x  string
	}{
		{0, "", "", "00"},
		{1, "61616262", "", "0161616262"},
		{3, "0001", "63636363", "03000163636363"},
		{200, "6666", "616161616161", "c8016666616161616161"},
	}
	for _, c := range cases {
		bloom, _ := hex.DecodeString(c.bloom)
		ha, _ := hex.DecodeString(c.ha)
		got := hex.EncodeToString(PackCGPBBR(c.depth, bloom, ha))
		if got != c.x {
			t.Errorf("PackCGPBBR(%d,%s,%s) = %s, want %s", c.depth, c.bloom, c.ha, got, c.x)
		}
	}
}

func TestSpanIDHexTo8Bytes(t *testing.T) {
	cases := []struct {
		s    string
		want string
		ok   bool
	}{
		{"", "0000000000000000", false},
		{"8ee27a115b6fa625", "8ee27a115b6fa625", true},
		{"abc", "0000000000000000", false}, // odd-length hex
		{"12345678", "0000000012345678", true},
		{"aabbccddeeff00112233", "ccddeeff00112233", true}, // longer than 8: keep last 8
		{"zz", "0000000000000000", false},                  // invalid hex chars
	}
	for _, c := range cases {
		got, ok := SpanIDHexTo8Bytes(c.s)
		gotHex := hex.EncodeToString(got[:])
		if ok != c.ok {
			t.Errorf("SpanIDHexTo8Bytes(%q) ok=%v, want %v", c.s, ok, c.ok)
		}
		if c.ok && gotHex != c.want {
			t.Errorf("SpanIDHexTo8Bytes(%q) = %s, want %s", c.s, gotHex, c.want)
		}
	}
}

func TestTraceIDHexTo16Bytes(t *testing.T) {
	cases := []struct {
		s, want string
	}{
		{"", "00000000000000000000000000000000"},
		{"928f188ef2409811", "0000000000000000928f188ef2409811"},
		{"928f188ef2409811928f188ef2409811", "928f188ef2409811928f188ef2409811"},
		{"abc", "00000000000000000000000000000000"},
		{"zz", "00000000000000000000000000000000"},
	}
	for _, c := range cases {
		got := TraceIDHexTo16Bytes(c.s)
		gotHex := hex.EncodeToString(got[:])
		if gotHex != c.want {
			t.Errorf("TraceIDHexTo16Bytes(%q) = %s, want %s", c.s, gotHex, c.want)
		}
	}
}

func TestPackSBridgeBR(t *testing.T) {
	ckpt := [4]byte{0x11, 0x22, 0x33, 0x44} // 4-byte window anchor (truncated root)
	zeros4 := [4]byte{}

	// A 3-level breadcrumb chain for a span at depth 5 (levels at depths 3,4,5).
	// The first level's parent is the checkpoint (no 2-byte fp); the deeper
	// levels carry the propagating parent's 2-byte fingerprint. EE rides per
	// level: levels 3,4 have none (varint(0)); level 5 carries [4,5].
	chain := []bcEntry{
		{ord: 10},
		{ord: 7, fp: 0xabcd, hasFp: true},
		{ord: 2, fp: 0xdef0, hasFp: true, ee: []int{4, 5}},
	}
	got1 := hex.EncodeToString(PackSBridgeBR(5, ckpt, chain, []byte{0xaa, 0xbb, 0xcc}))
	// 05 | 11223344 | 03 | [03 01 0a 00] [04 01 07 abcd 00] [05 01 02 def0 02 0405] | aabbcc
	want1 := "05112233440303010a00040107abcd00050102def0020405aabbcc"
	if got1 != want1 {
		t.Errorf("p1: got %s, want %s", got1, want1)
	}

	got2 := hex.EncodeToString(PackSBridgeBR(0, zeros4, nil, nil))
	want2 := "000000000000"
	if got2 != want2 {
		t.Errorf("p2: got %s, want %s", got2, want2)
	}

	// sbridgeBRSize must equal the serialized length for every shape.
	cases := []struct {
		depth int
		chain []bcEntry
		dee   []byte
	}{
		{5, chain, []byte{0xaa, 0xbb, 0xcc}},
		{0, nil, nil},
		{3, []bcEntry{{ord: 1, ee: []int{1, 2, 3}}, {ord: 99, fp: 0x1234, hasFp: true}}, nil},
	}
	for i, c := range cases {
		gotSize := sbridgeBRSize(c.depth, c.chain, c.dee)
		wantSize := len(PackSBridgeBR(c.depth, ckpt, c.chain, c.dee))
		if gotSize != wantSize {
			t.Errorf("case %d: sbridgeBRSize=%d != len(pack)=%d", i, gotSize, wantSize)
		}
	}
}

func TestEncodeDEEQuad(t *testing.T) {
	cases := []struct {
		traceHex string
		depth    int
		ownerFP  uint32
		seqs     []int
		want     string
	}{
		// layout: trace_id(16) || varint(depth) || owner_fp(4 BE) || varint(n) || n*varint(seq)
		{"928f188ef2409811", 4, 0xabcd1234, []int{1, 2, 3}, "0000000000000000928f188ef240981104abcd123403010203"},
		{"", 0, 0x00000000, nil, "00000000000000000000000000000000000000000000"},
		{"928f188ef2409811928f188ef2409811", 200, 0x12345678, []int{99}, "928f188ef2409811928f188ef2409811c801123456780163"},
	}
	for _, c := range cases {
		tid := TraceIDHexTo16Bytes(c.traceHex)
		got := hex.EncodeToString(EncodeDEEQuad(tid, c.depth, c.ownerFP, c.seqs))
		if got != c.want {
			t.Errorf("EncodeDEEQuad(%s,%d,%#x,%v) = %s, want %s", c.traceHex, c.depth, c.ownerFP, c.seqs, got, c.want)
		}
	}
}
