package bridge

import (
	"encoding/hex"
	"testing"
)

// All vectors generated by driving the Python helpers in trace_simulator.py.

type varintVec struct {
	n int
	x string
}

var varintVecs = []varintVec{
	{0, "00"},
	{1, "01"},
	{127, "7f"},
	{128, "8001"},
	{256, "8002"},
	{16383, "ff7f"},
	{16384, "808001"},
	{1 << 32, "8080808010"},
}

func TestVarintEncode(t *testing.T) {
	for _, v := range varintVecs {
		got := hex.EncodeToString(VarintEncode(v.n))
		if got != v.x {
			t.Errorf("VarintEncode(%d) = %s, want %s", v.n, got, v.x)
		}
		if want := len(v.x) / 2; VarintLen(v.n) != want {
			t.Errorf("VarintLen(%d) = %d, want %d", v.n, VarintLen(v.n), want)
		}
	}
}

func TestPackBR(t *testing.T) {
	cases := []struct {
		depth int
		bloom string
		want  string
	}{
		{0, "", "00"},
		{0, "ff01", "00ff01"},
		{1, "61616262", "0161616262"},
		{127, "00000000", "7f00000000"},
		{128, "ffffff", "8001ffffff"},
	}
	for _, c := range cases {
		bloom, _ := hex.DecodeString(c.bloom)
		got := hex.EncodeToString(PackBR(c.depth, bloom))
		if got != c.want {
			t.Errorf("PackBR(%d, %s) = %s, want %s", c.depth, c.bloom, got, c.want)
		}
	}
}

func TestHAAppendEntry(t *testing.T) {
	type step struct {
		sid     string
		depth   int
		want    string // empty want means HAAppendEntry should be a no-op (Python returned None)
		isNone  bool
	}
	steps := []step{
		{"8ee27a115b6fa625", 0, "8ee27a115b6fa62500", false},
		{"98655be61af2ecc4", 5, "8ee27a115b6fa6250098655be61af2ecc405", false},
		{"0", 7, "8ee27a115b6fa6250098655be61af2ecc405", true},  // Python returns None; ha unchanged
		{"zz", 9, "8ee27a115b6fa6250098655be61af2ecc405", true}, // ditto
	}
	ha := []byte{}
	for _, s := range steps {
		got := HAAppendEntry(ha, s.sid, s.depth)
		gotHex := hex.EncodeToString(got)
		if gotHex != s.want {
			t.Errorf("HAAppendEntry sid=%q depth=%d -> %s, want %s", s.sid, s.depth, gotHex, s.want)
		}
		ha = got
	}
}

func TestPackCGPBBR(t *testing.T) {
	cases := []struct {
		depth         int
		bloom, ha, x  string
	}{
		{0, "", "", "00"},
		{1, "61616262", "", "0161616262"},
		{3, "0001", "63636363", "03000163636363"},
		{200, "6666", "616161616161", "c8016666616161616161"},
	}
	for _, c := range cases {
		bloom, _ := hex.DecodeString(c.bloom)
		ha, _ := hex.DecodeString(c.ha)
		got := hex.EncodeToString(PackCGPBBR(c.depth, bloom, ha))
		if got != c.x {
			t.Errorf("PackCGPBBR(%d,%s,%s) = %s, want %s", c.depth, c.bloom, c.ha, got, c.x)
		}
	}
}

func TestSpanIDHexTo8Bytes(t *testing.T) {
	cases := []struct {
		s    string
		want string
		ok   bool
	}{
		{"", "0000000000000000", false},
		{"8ee27a115b6fa625", "8ee27a115b6fa625", true},
		{"abc", "0000000000000000", false}, // odd-length hex
		{"12345678", "0000000012345678", true},
		{"aabbccddeeff00112233", "ccddeeff00112233", true}, // longer than 8: keep last 8
		{"zz", "0000000000000000", false},                  // invalid hex chars
	}
	for _, c := range cases {
		got, ok := SpanIDHexTo8Bytes(c.s)
		gotHex := hex.EncodeToString(got[:])
		if ok != c.ok {
			t.Errorf("SpanIDHexTo8Bytes(%q) ok=%v, want %v", c.s, ok, c.ok)
		}
		if c.ok && gotHex != c.want {
			t.Errorf("SpanIDHexTo8Bytes(%q) = %s, want %s", c.s, gotHex, c.want)
		}
	}
}

func TestTraceIDHexTo16Bytes(t *testing.T) {
	cases := []struct {
		s, want string
	}{
		{"", "00000000000000000000000000000000"},
		{"928f188ef2409811", "0000000000000000928f188ef2409811"},
		{"928f188ef2409811928f188ef2409811", "928f188ef2409811928f188ef2409811"},
		{"abc", "00000000000000000000000000000000"},
		{"zz", "00000000000000000000000000000000"},
	}
	for _, c := range cases {
		got := TraceIDHexTo16Bytes(c.s)
		gotHex := hex.EncodeToString(got[:])
		if gotHex != c.want {
			t.Errorf("TraceIDHexTo16Bytes(%q) = %s, want %s", c.s, gotHex, c.want)
		}
	}
}

func TestPackSBridgeBR(t *testing.T) {
	ckpt := [8]byte{0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88}
	zeros8 := [8]byte{}

	got1 := hex.EncodeToString(PackSBridgeBR(
		5, ckpt,
		map[int][]int{3: {1, 2, 3}, 1: {10}, 2: {}},
		[]int{4, 5},
		[]byte{0xaa, 0xbb, 0xcc},
	))
	want1 := "0511223344556677880301010a02000303010203020405aabbcc"
	if got1 != want1 {
		t.Errorf("p1: got %s, want %s", got1, want1)
	}

	got2 := hex.EncodeToString(PackSBridgeBR(0, zeros8, map[int][]int{}, []int{}, nil))
	want2 := "0000000000000000000000"
	if got2 != want2 {
		t.Errorf("p2: got %s, want %s", got2, want2)
	}

	got3 := hex.EncodeToString(PackSBridgeBR(7, ckpt, map[int][]int{0: {9}}, []int{1, 2, 3, 4}, nil))
	want3 := "071122334455667788010001090401020304"
	if got3 != want3 {
		t.Errorf("p3: got %s, want %s", got3, want3)
	}
}

func TestEncodeDEETriple(t *testing.T) {
	cases := []struct {
		traceHex string
		depth    int
		seqs     []int
		want     string
	}{
		{"928f188ef2409811", 4, []int{1, 2, 3}, "0000000000000000928f188ef24098110403010203"},
		{"", 0, nil, "000000000000000000000000000000000000"},
		{"928f188ef2409811928f188ef2409811", 200, []int{99}, "928f188ef2409811928f188ef2409811c8010163"},
	}
	for _, c := range cases {
		tid := TraceIDHexTo16Bytes(c.traceHex)
		got := hex.EncodeToString(EncodeDEETriple(tid, c.depth, c.seqs))
		if got != c.want {
			t.Errorf("EncodeDEETriple(%s,%d,%v) = %s, want %s", c.traceHex, c.depth, c.seqs, got, c.want)
		}
	}
}
